[package]
name = "lso-app"
version.workspace = true
edition.workspace = true
default-run = "lso-app"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
lso-core = { path = "../crates/lso-core" }
lso-sensor = { path = "../crates/lso-sensor" }
lso-engine = { path = "../crates/lso-engine" }
lso-db = { path = "../crates/lso-db" }
tauri = { version = "2", features = [] }
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true

[lib]
name = "lso_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
