[package]
name = "lso-engine"
version.workspace = true
edition.workspace = true

[dependencies]
lso-core = { path = "../lso-core" }
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
